# Generated by Django 2.1.5 on 2019-01-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnews', '0004_storypoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created']},
        ),
    ]
