# Generated by Django 2.1.5 on 2019-01-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnews', '0005_auto_20190127_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='number_of_comments',
            field=models.IntegerField(default=0),
        ),
    ]
