# Generated by Django 2.1.5 on 2019-02-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnews', '0006_story_number_of_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='number_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
