# Generated by Django 2.1.5 on 2019-02-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnews', '0007_story_number_of_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='url_domain_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
