# Generated by Django 2.2.3 on 2019-07-24 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socialnews', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_body_text',
            field=models.TextField(blank=True, null=True, verbose_name='sotry body text (use markdown)'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='url'),
        ),
    ]
